### ISSUE TITLE
Release the final 1.1 release

### ISSUE THREAD

**Issue by tas50** [net-ssh/bcrypt_pbkdf-ruby#13]
Hey there @mfazekas,

It's been a while since the 1.1 RC release came out and we've been shipping that in Chef Infra Client without any problems. Any chance this release could get pushed up to Rubygems as full release?

**Comment by mfazekas** [comment]
@tas50 created a rc2 release with 3.0, can you confirm it's good to be released as final?!

**Comment by tas50** [comment]
Thanks for the super quick response @mfazekas. The PR is here:https://github.com/chef/chef/pull/10804 I'll run it through our build system.

**Comment by tas50** [comment]
@mfazekas Can you push up the w32 gem variants as well please?

**Comment by tisba** [comment]
Thanks for getting 1.1.0 out the door 🥳 

Reading the diff between 1.0.1 and 1.1.0 I assume that https://github.com/net-ssh/bcrypt_pbkdf-ruby/pull/15 and https://github.com/net-ssh/bcrypt_pbkdf-ruby/pull/15 are the most relevant changes, right? Just asking because the CHANGELOG has not been updated yet.
