### ISSUE TITLE
Should we bump to 2.0?

### ISSUE THREAD

**Issue by mfazekas** [net-ssh/bcrypt_pbkdf-ruby#8]
With the planned 1.1 we might be dropping older rubies on windows. (2.0 and 2.1) while those EOL 3 years ago, we might want to bump major version. 
We probably still compile/run on very old rubies, just our windows binary precompiler doesn't not build for them.

One thing is that our docs in net-ssh are documenting < 2.0, so bumping the version might be more trouble than worth.

https://github.com/net-ssh/net-ssh/blob/fc91300d7ee6299ba2fe4039cc8085aec9edb7f3/lib/net/ssh/authentication/ed25519_loader.rb#L27

**Comment by marcparadise** [comment]
Ordinairly,  update which makes it likely that code will stop working should receive a major version update, but it's easy for me to say this as someone uninvolved in the releases of net-ssh and bcrypt_pbkdf-ruby.

I did try to verify a direct build of the gem on windows under Ruby 2.1, but I could not build it -- attempting to bundle install prior to `rake` failed with a cert error from api.rubygems.org.   

 Given that, I do wonder how many people/systems are in the intersection of those using this gem on Windows, with Ruby < 2.2, _and_ will ever again run a `bundle update` for that software.  Particularly since `bundle update` will now fail by default on that version under windows without a [workaround](https://github.com/rubygems/rubygems/issues/1736#issuecomment-252074698)
 
When I consider in that context,  I'm more inclined to see a minor update as reasonable.

**Comment by lamont-granquist** [comment]
You should set a `spec.required_ruby_version = '>= 2.2'` explicitly in the gemspec and drop support for them entirely.

On relatively modern bundler + rubygems that will exclude the 1.1 version of the gem for consideration on rubies that are too old.  People will be able to gem install or bundle update successfully and it will exclude the 1.1 version from the solution set on rubies that are too old and will otherwise function normally.

There could still be people on 2.0 and 2.1 on ancient bundler + rubygems they would still solve for 2.2 and try to install it and fail but they get the error message back that its not supported, rather than having it mysteriously blow up in native compilation somewhere.

I don't think the underlying platform should be part of the external API and should not be covered by Semver (and is not in fact covered by Semver), so don't see the need for a major bump.  The fact that updates for old ruby 2.0/2.1 versions stop in the 1.1 version of this gem is not "breaking" the API, since updates are not part of the "API".

You might break people who haven't updated ruby, rubygems and bundler in 5+ years, but all of that is EOL at this point and that seems highly unreasonable.  The rubygems + bundler support matrix goes back very far and even those rubies can pick up recent enough versions so that it works (and the ruby version constraints against the required_ruby_version work in rubygems 2.x + bundler 1.x).

**Comment by tyler-ball** [comment]
IMO Lamont makes a case for leaving the version at `1.1`.

I would love to have a release rather than a pre-release because pre-releases (`.rc1`) wreck havoc on our internal appbundling tool. Is there anything I can do to help move towards a version decision and get a non-rc version released?

**Comment by tyler-ball** [comment]
Bumping this because it came up in one of our triage sessions. Anything I can do to help get a decision made on this and a release performed?

**Comment by mfazekas** [comment]
@tyler-ball i'm really sorry about the delays on this. Can you please ping me sunday or moday, i'll release it as minor version.

**Comment by tyler-ball** [comment]
Hey @mfazekas - this fell off my radar too! Is there anything I can do to help with the release now? Maybe just setting aside time?
